#!/usr/bin/env bash

# Configuration
SALT_PACKAGES="default"
SALT_BOOTSTRAP="https://bootstrap.saltstack.com"
SALT_BOOTSTRAP_ARGS=""

#
# Functions
#

function usage {
	echo ""
	echo "Usage: "
	echo "  $0 [package] ..."
	echo ""
	echo "Each \"package\" is a path to salt roots to be included."
	echo "A top.sls will be autogenerated with all the states in it."
	echo

	exit
}

function download_bootstrap {
	local destination="$1"

	if [[ $(python -c 'print(1)' 2>/dev/null) == "1" ]]; then
		echo "Downloading salt-bootstrap with Python"
		python -c 'import urllib; print urllib.urlopen("'"$SALT_BOOTSTRAP"'").read()' > "$destination"
	elif [[ $(which wget >/dev/null 2>&1; echo $?) == "0" ]]; then
		echo "Downloading salt-bootstrap with wget"
		wget -q -O "$destination" "$SALT_BOOTSTRAP"
	elif [[ $(which curl >/dev/null 2>&1; echo $?) == "0" ]]; then
		echo "Downloading salt-bootstrap with curl"
		curl -Lq "$SALT_BOOTSTRAP" > "$destination"
	else
		echo "Could not detect any tool capable of downloading salt-boostrap."
		exit
	fi
}

function bootstrap_salt {
	local bootstrap_file="salt-bootstrap.sh"

	if [[ $(which salt-call >/dev/null 2>&1; echo $?) != "0" ]]; then
		if [[ ! -f "$bootstrap_file" ]]; then
			download_bootstrap "$bootstrap_file"
		fi

		echo "Bootstrapping salt"
		bash "$bootstrap_file" $SALT_BOOTSTRAP_ARGS
	fi
}

function generate_top_sls {
	echo "Generating top.sls for the combined state trees"

	# PyYAML should be installed by Salt Stack
	python merge_top_sls.py $SALT_PACKAGES > "/srv/salt/top.sls"
}

function setup_salt_configuration {
	local salt="/srv/salt"
	local pillar="/srv/pillar"

	echo "Setting up Salt configuration"

	mkdir -p "$salt" "$pillar"
	touch "$pillar/top.sls"

	for pkg in $SALT_PACKAGES; do
		echo "Copying $pkg contents"
		cp -a "$pkg"/* "$salt"
	done

	generate_top_sls
}

function run_salt {
	salt-call --local state.highstate
}

#
# Script logic
#

# Permission check
if [[ "$UID" != "0" ]]; then
	echo "You need to run this script as root (or with sudo)."
	exit 1
fi

# Argument parsing, each argument is an additional salt package to add
for pkg in $@; do
	if [[ "$pkg" == "--help" ]] || [[ "$pkg" == "-h" ]] ; then
		usage
	fi

	SALT_PACKAGES="${SALT_PACKAGES} $pkg"
done

# Execute the steps
bootstrap_salt
setup_salt_configuration
run_salt
